version: '3.9'
    
volumes:
  prometheus_data:
  grafana_data:
  alerta_db:

networks:
  monitoring:

services:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/server_alerts.yml:/etc/prometheus/server_alerts.yml
      - ./prometheus/cosmos_alerts.yml:/etc/prometheus/cosmos_alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command: ['sh', '-c', 'envsubst < /etc/alertmanager/config.template.yml > /etc/alertmanager/config.yml && exec /bin/alertmanager --config.file=/etc/alertmanager/config.yml --storage.path=/alertmanager']
    expose:
      - 9093
    networks:
      - monitoring

  alerta_db:
    container_name: alerta_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - alerta_db:/var/lib/postgresql/data
      - ./alerta/alerta-init.sql:/docker-entrypoint-initdb.d/alerta-init.sql
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    networks:
      - monitoring

  alerta_web:
    container_name: alerta_web
    image: alerta/alerta-web:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://admin:admin@alerta_db:5432/monitoring
      - PLUGINS=reject,blackout
    expose:
      - 8080
    networks:
      - monitoring
    depends_on:
      - alerta_db

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - monitoring

  caddy:
    container_name: caddy
    image: caddy/caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - SERVER_IP=${SERVER_IP}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    ports:
      - 80:80
      - 443:443
    networks:
      - monitoring
